FROM debian:latest

ARG QT_VERSION=5.13.2
ARG NDK_VERSION=r19c
ARG SDK_INSTALL_PARAMS=platform-tool,build-tools-28.0.2,android-21
ARG QT_PACKAGES="qt,qt.qt5.5132,qt.qt5.5132.gcc_64,qt.qt5.5132.android_armv7"
ARG ANDROID_SDK_ROOT=/android-sdk-linux

MAINTAINER HomDX

RUN dpkg --add-architecture i386
RUN apt-get update

RUN apt-get install -y \
	wget \
	curl \
	unzip \
	git \
	make \
	lib32z1 \
	lib32ncurses6 \
	libbz2-1.0:i386 \
	lib32stdc++6 \
	&& apt-get clean

#install dependencies for Qt installer
RUN apt-get install -y \
	libgl1-mesa-glx \
	libglib2.0-0 \
	&& apt-get clean

#install dependencies for Qt modules
RUN apt-get install -y \
	libfontconfig1 \
	libdbus-1-3 \
	libx11-xcb1 \
	libnss3-dev \
	libasound2-dev \
	libxcomposite1 \
	libxrandr2 \
	libxcursor-dev \
	libegl1-mesa-dev \
	libxi-dev \
	libxss-dev \
	libxtst6 \
	libgl1-mesa-dev \
	&& apt install apt-transport-https ca-certificates wget dirmngr gnupg software-properties-common -y \
        && wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add - \
        && add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ \
        && apt update && apt install adoptopenjdk-8-hotspot -y \
        && apt-get clean

#Install CLANG
RUN     wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - \
	&& apt-add-repository --yes  "deb http://apt.llvm.org/buster/ llvm-toolchain-buster main" \
	&& apt update && apt list --upgradable && apt-get upgrade -y && apt install clang-3.9 lldb -y \
        && apt-get clean

ENV VERBOSE=1
ENV QT_CI_PACKAGES=$QT_PACKAGES

#COPY install-android-sdk /tmp/install-android-sdk
RUN wget https://raw.githubusercontent.com/homdx/qtci/513/bin/install-android-sdk --directory-prefix=/tmp \
	&&  chmod u+rx /tmp/install-android-sdk \
	&& /tmp/install-android-sdk $SDK_INSTALL_PARAMS

#dependencies for Qt installer
RUN apt-get install -y \
       libgl1-mesa-glx \
       libglib2.0-0 \
       && apt-get clean

ARG QT_VERSION=5.13.2
ARG NDK_VERSION=r19c
ARG ANDROID_SDK_ROOT=/android-sdk-linux

ARG PATH="/Qt/$QT_VERSION/android_armv7/bin/:${PATH}"
ARG ANDROID_NDK_ROOT="/android-ndk-$NDK_VERSION"
ARG ANDROID_SDK_ROOT="/android-sdk-linux"
ARG QT_HOME=/Qt/$QT_VERSION/


#COPY install-android-sdk /tmp/install-android-sdk
#RUN wget https://raw.githubusercontent.com/homdx/qtci/513/bin/install-android-sdk --directory-prefix=/tmp \
#	&&  chmod u+rx /tmp/install-android-sdk \
#&& /tmp/install-android-sdk $SDK_INSTALL_PARAMS




#download + install Qt
#COPY Makefile /Qt/5.13.2/Src/Makefile

#RUN mkdir -p /tmp/qt-installer \
#       && cd /tmp/qt-installer \
#       && wget https://raw.githubusercontent.com/homdx/qtci/master/bin/extract-qt-installer --directory-prefix=/tmp/qt-installer/ \
#       && wget https://raw.githubusercontent.com/homdx/qtci/master/recipes/install-qt --directory-prefix=/tmp/qt-installer/ \
#       && export PATH=$PATH:/tmp/qt-installer/ \
#       && chmod u+rx /tmp/qt-installer/extract-qt-installer \
#       && chmod u+rx /tmp/qt-installer/install-qt \
#       && bash /tmp/qt-installer/install-qt $QT_VERSION \
#       && rm -rf /tmp/qt-installer  \
#       && echo /build-from-source.sh

ARG QT_HASH=d498a097680eac88f5d0d750c0109f1d7e25366bd52ab50ae8014ea940ab86a1b3766b12f2f29a8743381f79272d7ea2fc2c764324867f313f6186afcb53e1cd

RUN apt-get install time -y  && cd / && curl -SL https://download.qt.io/archive/qt/5.13/5.13.2/single/qt-everywhere-src-5.13.2.tar.xz -o qt-5132.tar.gz && \
    set +ex && echo "${QT_HASH}  qt-5132.tar.gz" | sha512sum -c  \
&& time tar -xf qt-5132.tar.gz && date && rm qt-5132.tar.gz

RUN cd /android-sdk-linux/tools/bin && ./sdkmanager "build-tools;29.0.2" && \
echo build OpenSSL from sources && \
export NDK_VERSION=r19c && \
export    ANDROID_NDK_ARCH=arch-arm c && \
export    ANDROID_NDK_EABI=llvm c && \
export    ANDROID_NDK_HOST=linux-x86_64 c && \
export    ANDROID_NDK_TOOLCHAIN_PREFIX=arm-linux-androideabi c && \
export    ANDROID_NDK_TOOLCHAIN_VERSION=4.9 c && \
export DEBIAN_FRONTEND=noninteractive c && \
export ANDROID_NDK_HOME=/android-ndk-r19c && \
cd / && git clone https://github.com/homdx/android_openssl.git && cd /android_openssl && git checkout 5140 && \
cd /android_openssl/ && git checkout 5140  && echo patch -p0 ssl.patch \
&& mkdir ~/android && ln -s /android-ndk-r19c ~/android/ndk-bundle && cd /android_openssl && time ./build_ssl.sh \
&& echo build done && \
ls -la arm


COPY build-from-source.sh /build-from-source.sh

RUN time /build-from-source.sh && echo ok build && date || echo error build && date

#RUN mkdir -p /usr/local/Qt-5.13.2/android_armv7 && ln -s /usr/local/Qt-5.13.2/bin /usr/local/Qt-5.13.2/android_armv7/bin

RUN wget https://raw.githubusercontent.com/homdx/qtci/513/bin/build-android-gradle-project --directory-prefix=/root/ \
        && chmod u+rx /root/build-android-gradle-project

ARG ADBCACHE_HASH=2d79d59fb56374337f3b7b09712f3d2e92b6b494d9a386861fdffe3879246a0ca792ab9c295a20beb1835c063aff5736ea1c559ab6765dc490add4b9fc337bd5

#RUN mkdir /Qt5132 && cd /Qt5132 && wget https://github.com/homdx/qt-download-2/releases/download/3/qt-installed-5132.aa \
#   && wget https://github.com/homdx/qt-download-2/releases/download/3/qt-installed-5132.ab  \
#   && cat qt-installed-5132.?? > qt-5132.tar.gz && rm -vf qt-installed-5132.*  \
#   && set -ex && echo "${ADBCACHE_HASH}  qt-5132.tar.gz" | sha512sum -c  \
#   && time tar -xf qt-5132.tar.gz && date && ls /

#ENV PATH="/usr/local/$QT_VERSION/bin/:${PATH}"
ENV ANDROID_NDK_ROOT="/android-ndk-$NDK_VERSION"
ENV ANDROID_SDK_ROOT="/android-sdk-linux"
#ENV QT_HOME=/usr/local/$QT_VERSION/


#RUN ln -s /root/build-android-gradle-project /usr/bin/build-android-gradle-project

CMD tail -f /var/log/faillog
