#!/bin/bash
# QT-CI Project
# License: Apache-2.0
# https://github.com/benlau/qtci

# Install Android SDK to current folder

set -e #quit on error

if [ $# -lt 1 ];
then
    echo install-android-sdk packages
    echo
    echo Example:
    echo     install-android-sdk platform-tool,build-tools-20.0.0,android-19
    exit -1
fi

NDK_VERSION=${NDK_VERSION:=r19c}

# e.g: platform-tool,build-tools-29.0.2,android-19
PACKAGES1=$1
PACKAGES2=$2
PACKAGES3=$3

echo Downloading Android SDK...
#wget -c -nv https://dl.google.com/android/android-sdk_r23.0.2-linux.tgz
wget -c -nv https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip

echo Downloading Android NDK...
wget -c -nv https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-x86_64.zip

echo Extacting Android SDK...
#tar -zxf android-sdk_r23.0.2-linux.tgz
unzip sdk-tools-linux-4333796.zip

echo "Fix Malformed input or input contains unmappable characters: /usr/share/ca-certificates/mozilla/NetLock_Arany_=Class_Gold="
rm -vf /usr/share/ca-certificates/mozilla/NetLock_Arany*
rm -vf /usr/lib/ssl/certs/NetLock_Arany_=Class_Gold=_F*
echo Upgrading Android SDK...
echo install 1 $PACKAGES1
(sleep 5 ; while true ; do sleep 1 ; printf 'y\r\n' ; done ) | ./tools/bin/sdkmanager --install $PACKAGES1
echo install 2 $PACKAGES2
(sleep 5 ; while true ; do sleep 1 ; printf 'y\r\n' ; done ) | ./tools/bin/sdkmanager --install $PACKAGES2
echo install 3 $PACKAGES3
(sleep 5 ; while true ; do sleep 1 ; printf 'y\r\n' ; done ) | ./tools/bin/sdkmanager --install $PACKAGES3
echo Three packages are installed

#echo Update to latest version
#./tools/bin/sdkmanager --update
#$PACKAGES

echo Installing Android NDK...
(unzip android-ndk-${NDK_VERSION}-linux-x86_64.zip)

echo Android SDK and NDK installed
/tools/platform-tools/adb kill-server

echo Remove downloaded files
rm  -vf *.zip

#echo move to root folder
#mv tools /android-sdk-linux
#mv android-ndk-${NDK_VERSION} /
echo list tmp
ls -la /tmp
echo list root
ls -la /
#sleep 120
echo
echo export PATH=$PWD/android-sdk-linux/tools:$PATH
echo export ANDROID_NDK_ROOT=$PWD/android-ndk-${NDK_VERSION}
echo export ANDROID_SDK_ROOT=$PWD/android-sdk-linux

